# Hospital Operations Analytics
## Milestone 1: Data Collection and Preparation

 Module 1: Hospital Data Collection
 Module 2: Data Cleaning & Transformation

---

### Project Objective
The objective of this project is to collect, integrate, clean, transform,
and prepare hospital operational data for healthcare analytics and
business intelligence visualization.

### Milestone 1 Objectives
- Collect hospital operational data
- Integrate patient, department, staff, bed, equipment, and movement data
- Identify duplicate records
- Analyze missing values
- Standardize categorical information
- Normalize healthcare operational indicators
- Prepare a reliable dataset for Tableau/Power BI

### Expected Deliverables
1. hospital_raw_data.csv
2. data_collection.py
3. hospital_cleaned.csv
4. hospital_cleaning.ipynb

### Evaluation Criteria
- Dataset completeness greater than 95%
- Missing values less than 2% after cleaning
- Consistent operational metrics
- Duplicate records removed
- Standardized department names

In [1]:
# Step 1 - Import Required Libraries
import pandas as pd
import numpy as np
print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# Load directly using the file name
dataset_name = "Hospital_RawDataset_Updated.csv"
hospital_df = pd.read_csv(dataset_name)

print(f"Dataset '{dataset_name}' loaded successfully.")

Dataset 'Hospital_RawDataset_Updated.csv' loaded successfully.

In [3]:
# Get the number of rows and columns
rows, columns = hospital_df.shape

print("Number of Records (Rows):", rows)
print("Number of Attributes (Columns):", columns)

Number of Records (Rows): 10000
Number of Attributes (Columns): 49

In [4]:
# Display the first 5 records
print("First 5 Records:")
display(hospital_df.head())

First 5 Records:

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Transferred,Transfer_From_Department,Transfer_To_Department,Transfer_Date,Number_of_Transfers,Dept_ICU_Bed_Capacity_Derived,Dept_Staff_Capacity_Derived,Admissions_Rate_%_Derived,Staff_Utilization_%_Derived,Bed_Occupancy_Rate_%
0,HOSP00016,C K Hospital,Private,Mumbai,Maharashtra,General Medicine,DEPT004,Dr. Arjun Sharma,12,257,...,No,General Medicine,NaN,NaN,0,98,598,0.0,43.0,0.2
1,HOSP00019,Cure Well Hospital,Private,Bengaluru,Karnataka,General Surgery,DEPT010,Dr. Sneha Rao,15,288,...,No,General Surgery,NaN,NaN,0,100,583,0.2,49.4,0.2
2,HOSP00004,Yashoda Hospital,Private,Hyderabad,Telangana,Pulmonology,DEPT005,Dr. Priya Reddy,20,181,...,No,Pulmonology,NaN,NaN,0,97,590,0.0,30.7,0.2
3,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Pulmonology,DEPT005,Dr. Rahul Verma,23,170,...,Yes,Pulmonology,Cardiology,9/17/2025,1,99,597,0.2,28.5,0.4
4,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,ICU,DEPT009,Dr. Priya Reddy,34,116,...,No,ICU,NaN,NaN,0,100,576,0.0,20.1,0.6

In [5]:
# Display the last 5 records
print("Last 5 Records:")
display(hospital_df.tail())

Last 5 Records:

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Transferred,Transfer_From_Department,Transfer_To_Department,Transfer_Date,Number_of_Transfers,Dept_ICU_Bed_Capacity_Derived,Dept_Staff_Capacity_Derived,Admissions_Rate_%_Derived,Staff_Utilization_%_Derived,Bed_Occupancy_Rate_%
9995,HOSP00007,Care Hospital,Private,Delhi,Delhi,Orthopedics,DEPT003,Dr. Rahul Verma,33,371,...,No,Orthopedics,NaN,NaN,0,99,583,0.2,63.6,0.4
9996,HOSP00002,KIMS Hospital,Private,Vijayawada,Andhra Pradesh,Psychiatry,DEPT008,Dr. Arjun Sharma,50,506,...,Yes,Psychiatry,ICU,4/16/2026,1,100,581,0.0,87.1,0.2
9997,HOSP00004,Yashoda Hospital,Private,Hyderabad,Telangana,Neurology,DEPT002,Dr. Rahul Verma,14,516,...,No,Neurology,NaN,NaN,0,100,583,0.0,88.5,0.8
9998,HOSP00011,Tata Memorial Hospital,Government,Bengaluru,Karnataka,Orthopedics,DEPT003,Dr. Rahul Verma,37,159,...,No,Orthopedics,NaN,NaN,0,99,584,0.2,27.2,0.4
9999,HOSP00018,Deepak Hospital,Private,Chennai,Tamil Nadu,Orthopedics,DEPT003,Dr. Sneha Rao,26,165,...,No,Orthopedics,NaN,NaN,0,97,556,0.2,29.7,0.4

In [6]:
# Display all column names
print("Dataset Columns:\n")

for index, column in enumerate(hospital_df.columns, start=1):
    print(f"{index}. {column}")

Dataset Columns:

1. Hospital ID
2. Hospital Name
3. Hospital Type
4. City
5. State
6. Department
7. Department ID
8. Doctor
9. Nurses
10. Staff Count
11. Patient ID
12. Patient Name
13. Gender
14. Age
15. Admission Date
16. Discharge Date
17. Diagnosis
18. Treatment
19. Medication
20. Admission Type
21. Test Result
22. Blood Type
23. Beds Available
24. ICU Beds
25. Bed Number
26. Bed Occupied
27. Equipment
28. Length of Stay
29. Room No
30. Billing Amount
31. Insurance Provider
32. Readmission
33. Dept_Bed_Capacity_Derived
34. Beds_Occupied_Count
35. Equipment ID
36. Equipment Number
37. Equipment Status
38. Equipment_Total_Inventory
39. Equipment_Usage_Duration_Hours
40. Transferred
41. Transfer_From_Department
42. Transfer_To_Department
43. Transfer_Date
44. Number_of_Transfers
45. Dept_ICU_Bed_Capacity_Derived
46. Dept_Staff_Capacity_Derived
47. Admissions_Rate_%_Derived
48. Staff_Utilization_%_Derived
49. Bed_Occupancy_Rate_%

In [7]:
# Display data types and non-null counts
hospital_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 49 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hospital ID                     10000 non-null  object
 1   Hospital Name                   10000 non-null  object
 2   Hospital Type                   10000 non-null  object
 3   City                            10000 non-null  object
 4   State                           10000 non-null  object
 5   Department                      10000 non-null  object
 6   Department ID                   10000 non-null  object
 7   Doctor                          10000 non-null  object
 8   Nurses                          10000 non-null  int64
 9   Staff Count                     10000 non-null  int64
 10  Patient ID                      10000 non-null  object
 11  Patient Name                    10000 non-null  object
 12  Gender                          10000 non-null  object
 13  Age                             10000 non-null  int64
 14  Admission Date                  10000 non-null  object
 15  Discharge Date                  10000 non-null  object
 16  Diagnosis                       10000 non-null  object
 17  Treatment                       10000 non-null  object
 18  Medication                      10000 non-null  object
 19  Admission Type                  10000 non-null  object
 20  Test Result                     10000 non-null  object
 21  Blood Type                      10000 non-null  object
 22  Beds Available                  10000 non-null  int64
 23  ICU Beds                        10000 non-null  int64
 24  Bed Number                      10000 non-null  int64
 25  Bed Occupied                    10000 non-null  object
 26  Equipment                       10000 non-null  object
 27  Length of Stay                  10000 non-null  int64
 28  Room No                         10000 non-null  int64
 29  Billing Amount                  10000 non-null  int64
 30  Insurance Provider              7537 non-null   object
 31  Readmission                     10000 non-null  object
 32  Dept_Bed_Capacity_Derived       10000 non-null  int64
 33  Beds_Occupied_Count             10000 non-null  int64
 34  Equipment ID                    10000 non-null  object
 35  Equipment Number                10000 non-null  object
 36  Equipment Status                10000 non-null  object
 37  Equipment_Total_Inventory       10000 non-null  int64
 38  Equipment_Usage_Duration_Hours  10000 non-null  float64
 39  Transferred                     10000 non-null  object
 40  Transfer_From_Department        10000 non-null  object
 41  Transfer_To_Department          1760 non-null   object
 42  Transfer_Date                   1760 non-null   object
 43  Number_of_Transfers             10000 non-null  int64
 44  Dept_ICU_Bed_Capacity_Derived   10000 non-null  int64
 45  Dept_Staff_Capacity_Derived     10000 non-null  int64
 46  Admissions_Rate_%_Derived       10000 non-null  float64
 47  Staff_Utilization_%_Derived     10000 non-null  float64
 48  Bed_Occupancy_Rate_%            10000 non-null  float64
dtypes: float64(4), int64(15), object(30)
memory usage: 3.7+ MB

In [8]:
# STEP 2 - MISSING VALUE ANALYSIS
# Calculate the number of missing values in each column
missing_count = hospital_df.isnull().sum()

# Calculate missing percentage for each column
missing_percentage = (missing_count / len(hospital_df)) * 100

# Create a summary table
missing_summary = pd.DataFrame({
    "Missing Values": missing_count,
    "Missing Percentage": missing_percentage
})

# Display only columns containing missing values
missing_summary = missing_summary[
    missing_summary["Missing Values"] > 0
].sort_values(
    by="Missing Percentage",
    ascending=False
)

print("Missing Value Summary:")
display(missing_summary)

Missing Value Summary:

                        Missing Values  Missing Percentage
Transfer_To_Department            8240               82.40
Transfer_Date                     8240               82.40
Insurance Provider                2463               24.63

In [9]:
# DUPLICATE RECORD ANALYSIS
# Count completely duplicated rows
duplicate_count = hospital_df.duplicated().sum()

print("Number of Duplicate Records:", duplicate_count)

# Calculate duplicate percentage
duplicate_percentage = (
    duplicate_count / len(hospital_df)
) * 100

print(
    f"Duplicate Percentage: {duplicate_percentage:.2f}%"
)

Number of Duplicate Records: 0
Duplicate Percentage: 0.00%

In [10]:
# INITIAL DATA QUALITY SUMMARY
total_cells = hospital_df.shape[0] * hospital_df.shape[1]
total_missing = hospital_df.isnull().sum().sum()

# Calculate overall completeness
completeness_percentage = (
    (total_cells - total_missing) / total_cells
) * 100

print("==============================================")
print("   INITIAL HOSPITAL DATA QUALITY SUMMARY")
print("==============================================")
print(f"Total Records       : {hospital_df.shape[0]}")
print(f"Total Attributes    : {hospital_df.shape[1]}")
print(f"Total Missing Cells : {total_missing}")
print(f"Duplicate Records   : {duplicate_count}")
print(f"Data Completeness   : {completeness_percentage:.2f}%")
print("==============================================")

==============================================
   INITIAL HOSPITAL DATA QUALITY SUMMARY
==============================================
Total Records       : 10000
Total Attributes    : 49
Total Missing Cells : 18943
Duplicate Records   : 0
Data Completeness   : 96.13%
==============================================

In [14]:
# STEP 6. - HANDLE MISSING TRANSFER DEPARTMENT
# Create a copy of the dataset if not already done
clean_df = hospital_df.copy()

# Handle missing Transfer_To_Department values
clean_df["Transfer_To_Department"] = clean_df["Transfer_To_Department"].fillna("Not Transferred")

print("Missing Transfer_To_Department values handled.")
print("Remaining missing values:", clean_df["Transfer_To_Department"].isnull().sum())

Missing Transfer_To_Department values handled.
Remaining missing values: 0

In [15]:
# STEP 3 - HANDLE MISSING TRANSFER DATE
# A missing transfer date means that no transfer occurred.
# We preserve this information using a meaningful categorical label.

clean_df["Transfer_Date"] = (
    clean_df["Transfer_Date"]
    .fillna("Not Transferred")
)

print("Missing Transfer_Date values handled.")
print(
    "Remaining missing values:",
    clean_df["Transfer_Date"].isnull().sum()
)

Missing Transfer_Date values handled.
Remaining missing values: 0

In [16]:
# HANDLE MISSING INSURANCE INFORMATION
# Missing insurance information is retained as an explicit
# category rather than deleting patient records.

clean_df["Insurance Provider"] = (
    clean_df["Insurance Provider"]
    .fillna("Not Available")
)

print("Missing Insurance Provider values handled.")
print(
    "Remaining missing values:",
    clean_df["Insurance Provider"].isnull().sum()
)

Missing Insurance Provider values handled.
Remaining missing values: 0

In [21]:
# STEP 6.4 - VERIFY MISSING VALUE TREATMENT
# Calculate remaining missing values
remaining_missing = clean_df.isnull().sum()

# Keep only columns that still contain missing values
remaining_missing = remaining_missing[
    remaining_missing > 0
].sort_values(ascending=False)


print("POST-TREATMENT MISSING VALUE ANALYSIS")


if len(remaining_missing) == 0:
    print("No missing values remain in the dataset.")
else:
    print("Columns with remaining missing values:")
    display(remaining_missing)

POST-TREATMENT MISSING VALUE ANALYSIS
No missing values remain in the dataset.

In [23]:
# CALCULATE POST-TREATMENT COMPLETENESS

total_cells_after = (
    clean_df.shape[0] * clean_df.shape[1]
)

missing_cells_after = (
    clean_df.isnull().sum().sum()
)

completeness_after = (
    (total_cells_after - missing_cells_after)
    / total_cells_after
) * 100

missing_percentage_after = (
    missing_cells_after / total_cells_after
) * 100

print("=" * 60)
print("       DATA COMPLETENESS AFTER MISSING VALUE TREATMENT")
print("=" * 60)

print(f"Total Cells          : {total_cells_after}")
print(f"Missing Cells        : {missing_cells_after}")
print(f"Missing Percentage   : {missing_percentage_after:.2f}%")
print(f"Data Completeness    : {completeness_after:.2f}%")

print("=" * 60)

============================================================
       DATA COMPLETENESS AFTER MISSING VALUE TREATMENT
============================================================
Total Cells          : 490000
Missing Cells        : 0
Missing Percentage   : 0.00%
Data Completeness    : 100.00%
============================================================

In [24]:
#  INSPECT CURRENT DEPARTMENT NAMES
# Display all unique department names before standardization.
# This allows us to identify spelling, spacing, or capitalization
# inconsistencies before modifying the data.

department_before = (
    clean_df["Department"]
    .value_counts(dropna=False)
    .reset_index()
)

department_before.columns = [
    "Department",
    "Record_Count"
]
print(" DEPARTMENT NAMES BEFORE STANDARDIZATION")
display(department_before)
print("Total Unique Department Values:",
      clean_df["Department"].nunique())

 DEPARTMENT NAMES BEFORE STANDARDIZATION

         Department  Record_Count
0         Neurology          1033
1          Oncology          1031
2   General Surgery          1020
3        Psychiatry          1016
4               ICU          1010
5        Nephrology           999
6        Cardiology           991
7       Pulmonology           978
8  General Medicine           964
9       Orthopedics           958

Total Unique Department Values: 10

In [25]:
# CHECK FOR UNNECESSARY SPACES
# Identify department values containing leading or trailing spaces.
space_issues = clean_df[
    clean_df["Department"] != clean_df["Department"].str.strip()
]
print("DEPARTMENT SPACE VALIDATION")
print(
    "Records with leading/trailing spaces:",
    len(space_issues)
)

DEPARTMENT SPACE VALIDATION
Records with leading/trailing spaces: 0

In [26]:
# STANDARDIZE DEPARTMENT TEXT FORMAT
# Remove leading and trailing whitespace.
clean_df["Department"] = (
    clean_df["Department"]
    .astype(str)
    .str.strip()
)

# Replace multiple consecutive spaces with a single space.
clean_df["Department"] = (
    clean_df["Department"]
    .str.replace(r"\s+", " ", regex=True)
)

# Standardize capitalization using title case.
clean_df["Department"] = (
    clean_df["Department"]
    .str.title()
)
print("Department text formatting standardized successfully.")

Department text formatting standardized successfully.

In [27]:
# Convert date columns into datetime format
clean_df["Admission Date"] = pd.to_datetime(
    clean_df["Admission Date"], errors="coerce"
)

clean_df["Discharge Date"] = pd.to_datetime(
    clean_df["Discharge Date"], errors="coerce"
)

# Transfer_Date contains "Not Transferred", so convert only
# actual date values and preserve the meaningful text label.
clean_df["Transfer_Date"] = pd.to_datetime(
    clean_df["Transfer_Date"],
    errors="coerce"
)

print("Date standardization completed successfully. ")

Date standardization completed successfully.

C:\Users\Rutuja\AppData\Local\Temp\ipykernel_35612\2770508066.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clean_df["Transfer_Date"] = pd.to_datetime(

In [28]:
# Check the resulting data types
print(clean_df[
    ["Admission Date", "Discharge Date", "Transfer_Date"]
].dtypes)

Admission Date    datetime64[ns]
Discharge Date    datetime64[ns]
Transfer_Date     datetime64[ns]
dtype: object

Healthcare Indicator Validation

Validate important numerical healthcare indicators and identify
invalid or negative values.

In [29]:
numeric_columns = [
    "Age",
    "Nurses",
    "Staff Count",
    "Beds Available",
    "ICU Beds",
    "Length of Stay",
    "Billing Amount",
    "Equipment_Usage_Duration_Hours"
]

# Check negative values
negative_values = (clean_df[numeric_columns] < 0).sum()

print("Negative values in healthcare indicators:")
print(negative_values)

Negative values in healthcare indicators:
Age                               0
Nurses                            0
Staff Count                       0
Beds Available                    0
ICU Beds                          0
Length of Stay                    0
Billing Amount                    0
Equipment_Usage_Duration_Hours    0
dtype: int64

In [30]:
# Check basic statistics
clean_df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Age,10000.0,45.30390,25.952659,1.0,23.00,45.0,68.0,90.0
Nurses,10000.0,27.53610,13.249470,5.0,16.00,28.0,39.0,50.0
Staff Count,10000.0,341.42100,149.201603,80.0,214.75,343.0,470.0,600.0
Beds Available,10000.0,258.89330,139.770105,20.0,137.00,258.0,381.0,500.0
ICU Beds,10000.0,52.67590,27.745581,5.0,29.00,53.0,76.0,100.0
Length of Stay,10000.0,8.06840,4.309708,1.0,4.00,8.0,12.0,15.0
Billing Amount,10000.0,249684.16640,143528.556259,1080.0,127386.75,245232.0,371990.0,499893.0
Equipment_Usage_Duration_Hours,10000.0,35.85976,20.567494,0.5,18.10,35.7,53.5,72.0

## Data Transformation

Create derived healthcare attributes to make the dataset suitable
for analysis and dashboard development.

In [32]:
# Create Age Group
clean_df["Age Group"] = pd.cut(
    clean_df["Age"],
    bins=[0, 18, 35, 50, 65, 120],
    labels=[
        "0-18",
        "19-35",
        "36-50",
        "51-65",
        "65+"
    ]
)

# Create Admission Month
clean_df["Admission Month"] = (
    clean_df["Admission Date"].dt.month_name()
)

# Create Admission Year
clean_df["Admission Year"] = (
    clean_df["Admission Date"].dt.year
)

# Create Length of Stay Category
clean_df["LOS Category"] = pd.cut(
    clean_df["Length of Stay"],
    bins=[-1, 3, 7, 14, float("inf")],
    labels=[
        "Short Stay",
        "Medium Stay",
        "Long Stay",
        "Extended Stay"
    ]
)

print("Data transformation completed successfully. ")

Data transformation completed successfully.

In [33]:
# Display the newly created columns
clean_df[
    [
        "Age",
        "Age Group",
        "Admission Month",
        "Admission Year",
        "Length of Stay",
        "LOS Category"
    ]
].head()

   Age Age Group Admission Month  Admission Year  Length of Stay LOS Category
0   10      0-18        February            2026              14    Long Stay
1    3      0-18             May            2026               4  Medium Stay
2   49     36-50         January            2026               4  Medium Stay
3   37     36-50       September            2025              11    Long Stay
4   58     51-65       September            2025               3   Short Stay

In [35]:
# FIX - RESTORE NON-TRANSFERRED STATUS
# Patients without a transfer should have a meaningful label
# instead of a missing date value.

clean_df.loc[
    clean_df["Transfer_To_Department"] == "Not Transferred",
    "Transfer_Date"
] = "Not Transferred"

print("Transfer date values corrected successfully. ✅")
print("Remaining missing values:", clean_df.isnull().sum().sum())

Transfer date values corrected successfully. ✅
Remaining missing values: 0

C:\Users\Rutuja\AppData\Local\Temp\ipykernel_35612\2882650804.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Transferred' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  clean_df.loc[

In [45]:
# STEP 12 - FINAL DATA QUALITY VALIDATION
final_missing = clean_df.isnull().sum().sum()
final_duplicates = clean_df.duplicated().sum()


print("FINAL DATA QUALITY CHECK")


print("Records          :", len(clean_df))
print("Columns          :", len(clean_df.columns))
print("Missing Values   :", final_missing)
print("Duplicates       :", final_duplicates)

if final_missing == 0 and final_duplicates == 0:
    print("\nData Quality Check: PASSED ✅")
else:
    print("\nData Quality Check: REVIEW REQUIRED ⚠️")

FINAL DATA QUALITY CHECK
Records          : 10000
Columns          : 53
Missing Values   : 0
Duplicates       : 0

Data Quality Check: PASSED ✅

In [49]:
# STEP 13 - EXPORT CLEANED DATASET
import os

# Create output folder if it doesn't exist
output_dir = "output"
os.makedirs(output_dir, exist_ok=True)

# Export cleaned dataframe to CSV
cleaned_file_path = os.path.join(output_dir, "hospital_cleaned.csv")
clean_df.to_csv(cleaned_file_path, index=False)


print("EXPORT SUCCESSFUL 🚀")

print(f"File Saved At: {cleaned_file_path}")
print(f"Total Rows   : {clean_df.shape[0]}")
print(f"Total Columns: {clean_df.shape[1]}")

              EXPORT SUCCESSFUL 🚀
File Saved At: output\hospital_cleaned.csv
Total Rows   : 10000
Total Columns: 53

In [48]:
# STEP 14 - VERIFY EXPORTED CSV
# Read back exported CSV
exported_df = pd.read_csv(cleaned_file_path)

print("Verified Rows   :", len(exported_df))
print("Verified Columns:", len(exported_df.columns))
print("Null Values     :", exported_df.isnull().sum().sum())

if len(exported_df) == len(clean_df) and exported_df.isnull().sum().sum() == 0:
    print("\n MILESTONE 1 COMPLETE! Deliverables are ready.")
else:
    print("\n⚠️ Verification failed. Please re-check the export step.")

Verified Rows   : 10000
Verified Columns: 53
Null Values     : 0

 MILESTONE 1 COMPLETE! Deliverables are ready.